[package]
name = "aoc_2020"
version = "0.1.0"
authors = ["Michał Muskała <michal@muskala.eu>"]
edition = "2018"

[dependencies]
aoc-runner = "0.3"
aoc-runner-derive = "0.3"
lazy_static = "1.4"
regex = "1.4"
bit-set = "0.5"
